title: MOHAMED Button Blog
email: mohamedbuttongames@gmail.com
description:  Technology By MOHAMED Button Games.
baseurl: "blog" # the subpath of your site, e.g. /blog
url: "https://mohamed-button-games.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: M_Button_Games
github_username:  MOHAMED-Button-Games

# Build settings
theme: minima
plugins:
  - jekyll-feed
