title: MOHAMED Button Blog
email: mohamedbuttongames@gmail.com
description:  Technology By MOHAMED Button Games.
baseurl: "mohamedbuttonblog.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: M_Button_Games
github_username:  MOHAMED-Button-Games

# Build settings
theme: minima
plugins:
  - jekyll-feed